[WIP] Token Signing Algorithm Support
bento-platform/bento_authorization_service pull request #1
Opened 2023-04-27 05:27 UTC by brouillette

Proposal: add the `alg` property to  `IssuerAndClient-`and `IssuerAndSubject-` models

2023-04-28 12:34 UTC, davidlougheed commented
I don't think we should store algorithm in the database nor need to be able to run expressions against it. The list of valid JWT algorithms is provided by the OpenID config, and the correct algorithm is derived from there (albeit assuming the set of `id_token` algorithms works as a proxy for the access token JWTs).

2023-04-28 17:02 UTC, brouillette commented
I think it's important that we can control for this.

As listed [here](https://www.loginradius.com/blog/engineering/jwt-signing-algorithms/) , for example, `HS256` is considered a valid signing algorithm, though it is considered much less secure than, say, `RS256`. From one bento instance to another, it'll surely come in handy to be able to filter out tokens an operator deems unfit from any particular provider at a more granular level, depending on the service being accessed.

2023-04-28 17:06 UTC, davidlougheed commented
we can set up a way to forbid certain algorithms, that's a good point - but it doesn't make sense to put that at the grants level, since the grant applies to a subject, not a specific token (I am giving access to 'david'@'issuer.com'; the token algorithm doesn't factor into who I am)

one way to do what you're suggesting is to put a list of allowed algorithms in the config object and filter out any that don't match in `IdPManager` before decoding

2023-05-03 17:11 UTC, davidlougheed requested changes

2023-05-03 17:11 UTC, davidlougheed commented on bento_authorization_service/idp_manager.py
> +class GeneralIdPManagerError(Exception):
code style: classes should be separated by exactly 2 newlines

2023-05-03 17:11 UTC, davidlougheed commented on bento_authorization_service/idp_manager.py
> +class GeneralIdPManagerError(Exception):
also, rename this `IdPManagerError` and make it the base class for the previous class to nicely group related error types; then add a new subclass `IdPManagerBadAlgorithmError` and use that for token errors

2023-05-03 17:11 UTC, davidlougheed commented on bento_authorization_service/idp_manager.py
> +
code style: 2 lines between function defs/classes etc at top level

2023-05-03 17:11 UTC, davidlougheed commented on bento_authorization_service/config.py
> +    permitted_token_algorithms: frozenset = frozenset(["RS256", "ES256"])
add more supported algorithms by default - whatever is supported by keycloak (as alluded to below) minus whatever algorithms are insecure / what we don't want to support.

2023-05-03 17:11 UTC, davidlougheed commented on tests/test_evaluation.py
> +
2 newlines between functions

2023-05-03 17:11 UTC, davidlougheed commented on tests/test_evaluation.py
> +        res = await evaluate(idp_manager, db, sd.make_fresh_david_no_alg_encoded(), sd.RESOURCE_PROJECT_1, frozenset({P_QUERY_DATA}))
120 char max line length (will add a linter!)

2023-05-08 17:23 UTC, davidlougheed requested changes

2023-05-08 17:23 UTC, davidlougheed commented on bento_authorization_service/config.py
> +        ["RS256", "RSA-OAEP", "AES"]
RSA-OAEP is an encryption algorithm not a signing algorithm as far as I can tell. worth checking out https://auth.sd4h.ca/keycloak/realms/bentov2/.well-known/openid-configuration (specifically `id_token_signing_alg_values_supported` which should map pretty well to the access token too) to see which signing algorithms come with keycloak by default and then disabling any youve read are insecure.

2023-05-09 12:48 UTC, davidlougheed requested changes
one last thing and then good to merge

2023-05-09 12:48 UTC, davidlougheed commented on tests/shared_data.py
> +    "alg": TEST_TOKEN_SIGNING_ALG,
alg is not a JWT claim, it is in the header - so this shouldn't be included here / in token bodies.

2023-05-11 14:30 UTC, davidlougheed approved these changes
lgtm

2023-05-11 22:35 UTC, merged